from panda3d.core import VBase3
from pirates.piratesbase import PLocalizer
from pirates.battle import EnemyGlobals
from pirates.battle.EnemySkills import *
from pirates.pirate import AvatarTypes
from pirates.uberdog.UberDogGlobals import InventoryType
from pirates.inventory import ItemGlobals
BOSS_NPC_LIST = {
    '': {
        'AvatarType': None,
        'HpScale': 5,
        'MpScale': 1,
        'Level': None,
        'Weapon': None,
        'WeaponLevel': 0,
        'Skills': [],
        'SkillLevel': 0,
        'GoldScale': 2,
        'ModelScale': 1.10,
        'DamageScale': 1,
        'HighlightColor': VBase3(1) },
    'dynamicBoss_1': {
        'AvatarType': AvatarTypes.Muck,
        'Level': 14,
        'Weapon': EnemyGlobals.CUTLASS,
        'Skills': (InventoryType.CutlassSlash, EnemySkills.CUTLASS_CHOP, EnemySkills.CUTLASS_WILDSLASH, InventoryType.CutlassCleave, EnemySkills.CUTLASS_DOUBLESLASH),
        'HpScale': 5,
        'GoldScale': 2,
        'ModelScale': 1.3,
        'HighlightColor': VBase3(1, 0.5, 0.5) },
    '1154059362.19Shochet': {
        'AvatarType': AvatarTypes.GiantCrab,
        'Skills': (EnemySkills.DUAL_CLAW,),
        'Level': 15,
        'HpScale': 2,
        'GoldScale': 2,
        'ModelScale': 3,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1154059366.69Shochet': {
        'AvatarType': AvatarTypes.RancidFlyTrap,
        'Skills': (EnemySkills.FLYTRAP_SPIT,),
        'Level': 15,
        'HpScale': 2,
        'GoldScale': 2,
        'ModelScale': 3,
        'HighlightColor': VBase3(1, 0, 1) },
    '1169616489.03Shochet': {
        'AvatarType': AvatarTypes.TwistedStump,
        'Skills': (EnemySkills.STUMP_STOMP,),
        'Level': 15,
        'HpScale': 2,
        'GoldScale': 2,
        'ModelScale': 3,
        'HighlightColor': VBase3(1, 0, 0.5) },
    '1247517440.0jloehrle': {
        'AvatarType': AvatarTypes.Brigand,
        'Level': [9, 14],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.75,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1220906480.53mtucker': {
        'Level': [23, 30],
        'AvatarType': AvatarTypes.Cadaver,
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.75,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219434293.16mtucker': {
        'AvatarType': AvatarTypes.Grenadier,
        'Level': [18, 25],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.75,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1238440501.07piwanow': {
        'AvatarType': AvatarTypes.Zombie,
        'Level': [28, 35],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.75,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1239930457.38piwanow': {
        'AvatarType': AvatarTypes.Thug,
        'Level': 6,
        'HpScale': 2,
        'MpScale': 1.5,
        'Level': 6,
        'GoldScale': 2,
        'ModelScale': 1.2,
        'DamageScale': 1.3,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1238441187.46piwanow': {
        'AvatarType': AvatarTypes.Cadaver,
        'Level': [23, 30],
        'HpScale': 5,
        'MpScale': 3,
        'Level': 24,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219426331.38mtucker': {
        'AvatarType': AvatarTypes.CarrionKnife,
        'Level': [18, 25],
        'HpScale': 7,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.75,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1248740229.97robrusso': {
        'AvatarType': AvatarTypes.JollyRoger,
        'Level': 50,
        'HpScale': 1,
        'MpScale': 1,
        'GoldScale': 2,
        'ModelScale': 1.2,
        'DamageScale': 1,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1248740301.97robrusso': {
        'Skills': (EnemySkills.STUMP_STOMP, EnemySkills.DAVY_JONES_CLAW),
        'AvatarType': AvatarTypes.DavyJones,
        'Level': 73,
        'HpScale': 1,
        'MpScale': 1,
        'GoldScale': 2,
        'ModelScale': 1.2,
        'DamageScale': 1,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1274906957.35gcarranza': {
        'AvatarType': AvatarTypes.Kudgel,
        'Level': 30,
        'HpScale': 3.5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.0,
        'DamageScale': 2.0,
        'HighlightColor': VBase3(1, 1, 1) },
    '1274889994.04gcarranza': {
        'AvatarType': AvatarTypes.SpanishBossA,
        'Level': 40,
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.3,
        'DamageScale': 2.0,
        'HighlightColor': VBase3(1, 1, 1) },
    '1291327895.46jloehrle': {
        'AvatarType': AvatarTypes.SpanishBossA,
        'Level': 50,
        'HpScale': 50,
        'MpScale': 10,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 6.0,
        'HighlightColor': VBase3(1, 1, 1),
        'DropAmount': 2,
        'DropRate': 100,
        'RarityDict': {
            ItemGlobals.FAMED: 15,
            ItemGlobals.LEGENDARY: 10 } },
    '1302895055.78jloehrle': {
        'AvatarType': AvatarTypes.SpanishBossA,
        'HpScale': 5,
        'MpScale': 3,
        'Level': 25,
        'GoldScale': 2,
        'ModelScale': 1.3,
        'DamageScale': 2.0,
        'HighlightColor': VBase3(1, 1, 1) },
    '1303260680.08jloehrle': {
        'AvatarType': AvatarTypes.SpanishBossA,
        'HpScale': 5,
        'MpScale': 3,
        'Level': 35,
        'GoldScale': 2,
        'ModelScale': 1.0,
        'DamageScale': 3.0,
        'HighlightColor': VBase3(1, 1, 1) },
    '1303331892.2jloehrle': {
        'AvatarType': AvatarTypes.FrenchBossA,
        'HpScale': 5,
        'MpScale': 3,
        'Level': 35,
        'GoldScale': 2,
        'ModelScale': 1.0,
        'DamageScale': 3.0,
        'HighlightColor': VBase3(1, 1, 1) },
    '1219352693.09mtucker': {
        'AvatarType': AvatarTypes.Assassin,
        'Level': [28, 35],
        'HpScale': 10,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.75,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219367627.94mtucker': {
        'AvatarType': AvatarTypes.Assassin,
        'Level': [28, 35],
        'HpScale': 10,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.75,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219339266.79mtucker': {
        'AvatarType': AvatarTypes.Grunt,
        'Level': [13, 19],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.10,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219277508.79mtucker': {
        'AvatarType': AvatarTypes.Bonecracker,
        'Level': [13, 19],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1219277509.79mtucker': {
        'AvatarType': AvatarTypes.Bonecracker,
        'Level': [4, 9],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1244583168.0jloehrle0': {
        'AvatarType': AvatarTypes.SandStalker,
        'Level': [18, 25],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1244833920.0jloehrle': {
        'AvatarType': AvatarTypes.SandStalker,
        'Level': [13, 19],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1218760329.71mtucker': {
        'AvatarType': AvatarTypes.RipTail,
        'Level': [2, 5],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.0,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1218760328.71mtucker': {
        'AvatarType': AvatarTypes.RipTail,
        'Level': [13, 20],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.0,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1244657664.0jloehrle1': {
        'AvatarType': AvatarTypes.Bowbreaker,
        'Level': [33, 40],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 1.5,
        'DamageScale': 2.0,
        'HighlightColor': VBase3(0, 1, 0.5) },
    '1244832512.0jloehrle': {
        'AvatarTypes': AvatarTypes.Devilwing,
        'Level': [15, 25],
        'HpScale': 5,
        'MpScale': 3,
        'GoldScale': 2,
        'ModelScale': 2.0,
        'DamageScale': 1.5,
        'HighlightColor': VBase3(0, 1, 0.5) }}
