from direct.distributed.MsgTypes import *

OTP_DO_ID_PIRATES = 500
OTP_DO_ID_CLIENT_SERVICES_MANAGER = 1000
OTP_DO_ID_PIRATES_TRAVEL_AGENT = 1001
OTP_DO_ID_PIRATES_FRIENDS_MANAGER = 1002
OTP_DO_ID_PIRATES_CREW_MATCH_MANAGER = 1003
OTP_DO_ID_PIRATES_MATCH_MAKER = 1004
OTP_DO_ID_PIRATES_GUILD_MANAGER = 1005
OTP_ZONE_ID_INVALID = 0
OTP_ZONE_ID_OLD_QUIET_ZONE = 1
OTP_ZONE_ID_MANAGEMENT = 2
OTP_ZONE_ID_DISTRICTS = 3
OTP_ZONE_ID_DISTRICTS_STATS = 4
OTP_ZONE_ID_ELEMENTS = 5
