from panda3d.core import Point3, VBase3, Vec4, Vec3
objectStruct = {
    'Interact Links': [],
    'Objects': {
        '1156207773.33dzlu0': {
            'Type': 'Building Interior',
            'Name': '',
            'AdditionalData': [
                'interior_tavern'],
            'Instanced': True,
            'Objects': {
                '1168022298.47Shochet': {
                    'Type': 'Townsperson',
                    'Category': 'Cast',
                    'AnimSet': 'sit_cards',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'models/char/jg_2000',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'Hpr': VBase3(30.983, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-37.996, -9.968, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1168022348.66Shochet': {
                    'Type': 'Townsperson',
                    'Category': 'Bartender',
                    'AnimSet': 'bar_wipe',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': '',
                    'Hpr': VBase3(-180.0, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(4.0819, 34.716, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1169070429.72mike': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'AnimSet': 'idleB',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'Hpr': VBase3(-177.336, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-38.496, -2.185, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1172629888.0mike': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(-145.741, -1.8819, 0.0),
                    'Objects': { },
                    'Pos': Point3(-37.475, -10.801, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/chair_bar' } },
                '1172630016.0mike': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(-53.826, 0.0, 0.0),
                    'Objects': { },
                    'Pos': Point3(-19.359, 7.4039, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/chair_bar' } },
                '1172630144.0mike': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'AnimSet': 'sit_sleep',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': '',
                    'Hpr': VBase3(125.411, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-20.123, 6.8158, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1173146624.0mike': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(64.305, 0.0, 0.0),
                    'Objects': { },
                    'Pos': Point3(-33.347, 10.106, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/chair_bar' } },
                '1174954368.0jubutler': {
                    'Type': 'Townsperson',
                    'Category': 'Cast',
                    'AnimSet': 'sit_cards',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'models/char/js_2000',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Hpr': VBase3(-79.509, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-48.2078, -9.5903, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'Private Only',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1175650176.0dxschafe': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'Aggro Radius': '12.0000',
                    'AnimSet': 'bar_talk01',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': '',
                    'Hpr': VBase3(-74.328, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-21.556, 30.192, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1178320768.0dchiappe': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'AnimSet': 'bar_talk03',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': '',
                    'Hpr': VBase3(104.634, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-17.25, 30.423, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1187306240.0dxschafe': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'Aggro Radius': '12.0000',
                    'AnimSet': 'idleC',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': '',
                    'Hpr': VBase3(-140.434, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-49.258, 32.393, 1.05),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1187306496.0dxschafe': {
                    'Type': 'Jugs_and_Jars',
                    'DisableCollision': False,
                    'Hpr': VBase3(0.0, 0.0, 0.0),
                    'Pos': Point3(-52.274, 31.635, 3.956),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/winebottle_B' } },
                '1187306496.0dxschafe0': {
                    'Type': 'Jugs_and_Jars',
                    'DisableCollision': False,
                    'Hpr': VBase3(0.0, 0.0, 0.0),
                    'Pos': Point3(10.497, 105.511, 12.791),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/winebottle_B' } },
                '1187306496.0dxschafe1': {
                    'Type': 'Jugs_and_Jars',
                    'DisableCollision': False,
                    'Hpr': VBase3(87.40, 0.0, 0.0),
                    'Pos': Point3(-52.899, 32.796, 4.03),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/waterpitcher' } },
                '1187306624.0dxschafe': {
                    'Type': 'Cups',
                    'DisableCollision': False,
                    'Hpr': VBase3(0.0, 0.0, 0.0),
                    'Pos': Point3(-50.991, 31.314, 3.9528),
                    'Scale': VBase3(0.5, 0.5, 0.5),
                    'Visual': {
                        'Model': 'models/props/cup_tin' } },
                '1190740736.0dxschafe1': {
                    'Type': 'Parlor Game',
                    'Category': 'Holdem',
                    'BetMultiplier': '1',
                    'GameVariation': 'Normal',
                    'Hpr': Point3(0.0, 0.0, 0.0),
                    'Pos': Point3(-16.233, -6.992, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/table_bar_round_parlor' } },
                '1190742272.0dxschafe1': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': Point3(0.0, 0.0, 0.0),
                    'Pos': Point3(-42.445, -6.7518, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/table_bar_round' } },
                '1190742272.0dxschafe2': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(14.196, 0.0, 0.0),
                    'Objects': { },
                    'Pos': Point3(-44.2508, -0.90700, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/chair_bar' } },
                '1190742272.0dxschafe3': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(107.08, 0.0, 0.0),
                    'Objects': { },
                    'Pos': Point3(-48.868, -9.75, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/chair_bar' } },
                '1190742400.0dxschafe': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'AnimSet': 'sit_cards',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'Hpr': VBase3(-151.348, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(-42.158, -0.522, 1.0),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'Private Status': 'All',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Villager',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 },
                '1190742784.0dxschafe': {
                    'Type': 'Cups',
                    'DisableCollision': False,
                    'Hpr': Point3(0.0, 0.0, 0.0),
                    'Pos': Point3(-41.658, -2.7829, 3.8968),
                    'Scale': VBase3(0.751, 0.751, 0.751),
                    'Visual': {
                        'Model': 'models/props/cup_tin' } },
                '1190742912.0dxschafe': {
                    'Type': 'Cups',
                    'DisableCollision': False,
                    'Hpr': VBase3(170.519, 0.0, 0.0),
                    'Pos': Point3(-40.631, -9.566, 3.9220),
                    'Scale': VBase3(1.931, 1.931, 1.931),
                    'Visual': {
                        'Model': 'models/props/cup_tin-old' } },
                '1190743040.0dxschafe': {
                    'Type': 'Jugs_and_Jars',
                    'DisableCollision': False,
                    'Hpr': Point3(0.0, 0.0, 0.0),
                    'Pos': Point3(-41.668, -9.906, 3.9008),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/winebottle_A' } },
                '1190743040.0dxschafe0': {
                    'Type': 'Jugs_and_Jars',
                    'DisableCollision': False,
                    'Hpr': Point3(0.0, 0.0, 0.0),
                    'Pos': Point3(-44.645, -6.984, 3.923),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Model': 'models/props/bottle_red' } },
                '1196380664.47akelts': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(93.793, 0.0, 0.0),
                    'Pos': Point3(-22.405, 29.9578, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Color': (0.83921568627450982, 0.810000, 0.77254901960784317, 1.0),
                        'Model': 'models/props/stool_bar_tall' } },
                '1196380706.33akelts': {
                    'Type': 'Furniture',
                    'DisableCollision': False,
                    'Hpr': VBase3(93.793, 0.0, 0.0),
                    'Pos': Point3(-15.103, 30.824, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'Visual': {
                        'Color': (0.810000, 0.790000, 0.75294117647058822, 1.0),
                        'Model': 'models/props/stool_bar_tall' } },
                '1206126048.2dxschafe': {
                    'Type': 'Door Locator Node',
                    'Name': 'door_locator',
                    'Hpr': VBase3(0.0, 0.0, 0.0),
                    'Pos': Point3(29.010, -38.82, 0.59798),
                    'Scale': VBase3(1.0, 1.0, 1.0) },
                '1206126049.56dxschafe': {
                    'Type': 'Door Locator Node',
                    'Name': 'door_locator_2',
                    'Hpr': VBase3(-180.0, 0.0, 0.0),
                    'Pos': Point3(-42.9368, 40.889, 1.0),
                    'Scale': VBase3(1.0, 1.0, 1.0) },
                '1229139756.35mtucker': {
                    'Type': 'Townsperson',
                    'Category': 'Commoner',
                    'AnimSet': 'default',
                    'AuraFX': 'None',
                    'Boss': False,
                    'CustomModel': 'None',
                    'DNA': '1229139756.35mtucker',
                    'GhostColor': 'None',
                    'GhostFX': 0,
                    'Greeting Animation': '',
                    'HelpID': 'NONE',
                    'Holiday': 'ValentinesDay',
                    'Hpr': VBase3(128.596, 0.0, 0.0),
                    'Instanced World': 'None',
                    'Level': '37',
                    'Notice Animation 1': '',
                    'Notice Animation 2': '',
                    'Patrol Radius': '12.0000',
                    'Pos': Point3(20.747, 17.25, 1.0169),
                    'PoseAnim': '',
                    'PoseFrame': '',
                    'PropFXLeft': 'None',
                    'PropFXRight': 'None',
                    'PropLeft': 'None',
                    'PropRight': 'None',
                    'Respawns': True,
                    'Scale': VBase3(1.0, 1.0, 1.0),
                    'ShopID': 'PORT_ROYAL_DEFAULTS',
                    'Start State': 'Idle',
                    'StartFrame': '0',
                    'Team': 'Player',
                    'TrailFX': 'None',
                    'TrailLeft': 'None',
                    'TrailRight': 'None',
                    'VisSize': '',
                    'Zombie': False,
                    'spawnTimeAlt': '',
                    'spawnTimeBegin': 0.0,
                    'spawnTimeEnd': 0.0 } },
            'Visual': {
                'Color': (0.848, 0.815, 0.728, 1.0),
                'Model': 'models/buildings/interior_tavern' } } },
    'Node Links': [],
    'Layers': { },
    'ObjectIds': {
        '1156207773.33dzlu0': '["Objects"]["1156207773.33dzlu0"]',
        '1168022298.47Shochet': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1168022298.47Shochet"]',
        '1168022348.66Shochet': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1168022348.66Shochet"]',
        '1169070429.72mike': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1169070429.72mike"]',
        '1172629888.0mike': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1172629888.0mike"]',
        '1172630016.0mike': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1172630016.0mike"]',
        '1172630144.0mike': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1172630144.0mike"]',
        '1173146624.0mike': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1173146624.0mike"]',
        '1174954368.0jubutler': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1174954368.0jubutler"]',
        '1175650176.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1175650176.0dxschafe"]',
        '1178320768.0dchiappe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1178320768.0dchiappe"]',
        '1187306240.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1187306240.0dxschafe"]',
        '1187306496.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1187306496.0dxschafe"]',
        '1187306496.0dxschafe0': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1187306496.0dxschafe0"]',
        '1187306496.0dxschafe1': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1187306496.0dxschafe1"]',
        '1187306624.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1187306624.0dxschafe"]',
        '1190740736.0dxschafe1': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190740736.0dxschafe1"]',
        '1190742272.0dxschafe1': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742272.0dxschafe1"]',
        '1190742272.0dxschafe2': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742272.0dxschafe2"]',
        '1190742272.0dxschafe3': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742272.0dxschafe3"]',
        '1190742400.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742400.0dxschafe"]',
        '1190742784.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742784.0dxschafe"]',
        '1190742912.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190742912.0dxschafe"]',
        '1190743040.0dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190743040.0dxschafe"]',
        '1190743040.0dxschafe0': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1190743040.0dxschafe0"]',
        '1196380664.47akelts': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1196380664.47akelts"]',
        '1196380706.33akelts': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1196380706.33akelts"]',
        '1206126048.2dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1206126048.2dxschafe"]',
        '1206126049.56dxschafe': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1206126049.56dxschafe"]',
        '1229139756.35mtucker': '["Objects"]["1156207773.33dzlu0"]["Objects"]["1229139756.35mtucker"]' } }
extraInfo = {
    'camPos': Point3(0, -14, 0.5),
    'camHpr': VBase3(0, 0, 0),
    'focalLength': 0.65799999237100004,
    'skyState': -2,
    'fog': 0 }
